#!/bin/bash

##I2P-config for I2PBerry

if [ -e /home/pi/.config/i2p.run ]; then

   dpkg-reconfigure i2p

else

echo "UNPACKING JAVA JDK"

mkdir -p -v /opt/java

tar xvzf /home/pi/jdk-8-fcs-b128-linux-arm-vfp-hflt-31_jan_2014.tar.gz

mv -v /home/pi/jdk1.8.0 /opt/java

  echo "JAVA_HOME="/opt/java/jdk1.8.0"" >> /etc/enviroment

  echo "export JAVA_HOME="/opt/java/jdk1.8.0"" >> ~/.bashrc
  echo "export PATH=$PATH:$JAVA_HOME/bin" >> ~/.bashrc

apt-get update

apt-get install i2p i2p-keyring

touch /home/pi/.config/i2p.run

dpkg-reconfigure i2p

fi
